CREATE DATABASE IF NOT EXISTS event_db;
USE event_db;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100),
  username VARCHAR(50),
  password VARCHAR(255)
);